import { computeLeadScore } from './bdrScoring.js';

const now = new Date().toISOString().split('T')[0];

const RAW_LEADS = [
  { id:'lead_001', company:'Deutsche Telekom', country:'Germany', industry:'Telco', employees:216000, source:'outbound_cold', status:'qualifying', contact_name:'Klaus Becker', contact_title:'Chief AI Officer', score_fit:5,score_intent:4,score_budget:5,score_decision_access:4,score_timeline:3,score_pain:4,score_compelling_event:4,score_champion:3,score_technical_fit:4,score_strategic_value:5, use_case_description:'Internal AI assistant for 50k+ support agents; GDPR-compliant LLM processing.', competitive_landscape:'Testing Azure OpenAI', compliance_context:'GDPR + NIS2 + BaFin-adjacent', technical_environment:'Azure stack, Python/FastAPI services', discovery_notes:'CISO signed off on API data processing. Budget is €1.2M for AI tooling this year.', next_steps:'Technical pilot scoping call booked', date_added:now, updated_at:now },
  { id:'lead_002', company:'Revolut', country:'UK', industry:'Fintech', employees:8000, source:'inbound_web', status:'qualified', contact_name:'Nik Storonsky', contact_title:'CEO', score_fit:5,score_intent:5,score_budget:4,score_decision_access:5,score_timeline:5,score_pain:5,score_compelling_event:5,score_champion:5,score_technical_fit:5,score_strategic_value:5, use_case_description:'Fraud narrative generation + customer support deflection. Need 99.9% uptime SLA.', competitive_landscape:'Evaluating Anthropic vs GPT-4o', compliance_context:'FCA regulated, SOC2 required', technical_environment:'GCP, Kotlin microservices', discovery_notes:'Nik involved directly. €500K budget confirmed. Wants pilot in 3 weeks.', next_steps:'AE intro call this Friday', date_added:now, updated_at:now },
  { id:'lead_003', company:'Sanofi', country:'France', industry:'Pharma', employees:100000, source:'inbound_event', status:'qualifying', contact_name:'Paul Hudson', contact_title:'VP Data Science', score_fit:4,score_intent:3,score_budget:5,score_decision_access:3,score_timeline:2,score_pain:3,score_compelling_event:2,score_champion:3,score_technical_fit:3,score_strategic_value:4, use_case_description:'Medical literature summarisation for R&D teams. 500+ researchers.', competitive_landscape:'None — first AI API eval', compliance_context:'EU MDR, GDPR, ICH Q9', technical_environment:'On-prem with Azure lift', discovery_notes:'No budget line yet. Procurement takes 4+ months. Strong technical interest.', next_steps:'Send SOC2 + GDPR DPA docs', date_added:now, updated_at:now },
  { id:'lead_004', company:'Klarna', country:'Sweden', industry:'Fintech', employees:3500, source:'outbound_sequence', status:'handed_off', contact_name:'Sebastian Siemiatkowski', contact_title:'CEO', score_fit:5,score_intent:5,score_budget:5,score_decision_access:5,score_timeline:5,score_pain:5,score_compelling_event:5,score_champion:5,score_technical_fit:5,score_strategic_value:5, use_case_description:'AI-powered customer service — replacing 700-agent team with Claude.', competitive_landscape:'Previously used GPT, switching to Anthropic for reliability', compliance_context:'PCI-DSS, GDPR, FCA', technical_environment:'AWS, React/Node.js', discovery_notes:'Deal in closing. €800K ACV. Sebastian directly engaged.', next_steps:'Contract review with legal', date_added:now, updated_at:now },
  { id:'lead_005', company:'N26', country:'Germany', industry:'Fintech', employees:1500, source:'inbound_referral', status:'qualifying', contact_name:'Valentin Stalf', contact_title:'CTO', score_fit:4,score_intent:4,score_budget:3,score_decision_access:4,score_timeline:3,score_pain:4,score_compelling_event:3,score_champion:4,score_technical_fit:4,score_strategic_value:4, use_case_description:'Transaction anomaly explanation and dispute resolution chatbot.', competitive_landscape:'In-house fine-tuned model (not working well)', compliance_context:'BaFin, GDPR', technical_environment:'GCP, Go microservices', discovery_notes:'Budget ~€200K. CTO is champion. Procurement simple (startup-ish).', next_steps:'Technical deep-dive next week', date_added:now, updated_at:now },
  { id:'lead_006', company:'Deliveroo', country:'UK', industry:'Logistics/Tech', employees:3000, source:'outbound_cold', status:'new', contact_name:'Will Shu', contact_title:'Head of ML', score_fit:3,score_intent:2,score_budget:3,score_decision_access:2,score_timeline:2,score_pain:3,score_compelling_event:2,score_champion:2,score_technical_fit:3,score_strategic_value:3, use_case_description:'Rider communication personalisation and restaurant menu optimisation.', competitive_landscape:'Internal ML team resistant to external APIs', compliance_context:'GDPR, UK-GDPR', technical_environment:'AWS, Python', discovery_notes:'No meeting yet. Outbound cold. Need to find ML champion.', next_steps:'Follow up on LinkedIn cold message', date_added:now, updated_at:now },
  { id:'lead_007', company:'BNP Paribas', country:'France', industry:'Finance', employees:193000, source:'partner', status:'qualifying', contact_name:'Jean-Laurent Bonnafé', contact_title:'Group CDO', score_fit:5,score_intent:4,score_budget:5,score_decision_access:3,score_timeline:2,score_pain:4,score_compelling_event:3,score_champion:3,score_technical_fit:3,score_strategic_value:5, use_case_description:'Regulatory document processing (MiFID II reports, ESMA filings). 10M+ docs/year.', competitive_landscape:'Azure OpenAI (compliance team blocks external AI)', compliance_context:'DORA, MiFID II, GDPR, ACPR', technical_environment:'On-prem, IBM stack, migrating to GCP', discovery_notes:'Partner intro via Capgemini. Procurement 6-9 months. €2M+ potential.', next_steps:'Executive briefing with CISO + CDO', date_added:now, updated_at:now },
  { id:'lead_008', company:'Stripe', country:'Ireland', industry:'Fintech', employees:8000, source:'inbound_web', status:'qualified', contact_name:'Patrick Collison', contact_title:'VP Engineering', score_fit:5,score_intent:5,score_budget:5,score_decision_access:5,score_timeline:4,score_pain:5,score_compelling_event:4,score_champion:5,score_technical_fit:5,score_strategic_value:5, use_case_description:'Developer documentation AI, Stripe Radar fraud explanation, internal tooling.', competitive_landscape:'Heavy OpenAI user — evaluating for SOC2 + reliability', compliance_context:'PCI-DSS Level 1, GDPR', technical_environment:'AWS, Ruby/Go, heavy API usage', discovery_notes:'Technical champion confirmed. €600K budget. Want 3-month pilot with SLA guarantee.', next_steps:'Pilot scope doc to send by EOW', date_added:now, updated_at:now },
  { id:'lead_009', company:'Zalando', country:'Germany', industry:'E-commerce', employees:17000, source:'outbound_cold', status:'new', contact_name:'Robert Gentz', contact_title:'Chief Product Officer', score_fit:3,score_intent:2,score_budget:4,score_decision_access:2,score_timeline:3,score_pain:3,score_compelling_event:3,score_champion:2,score_technical_fit:3,score_strategic_value:3, use_case_description:'Fashion product description generation + styling recommendations.', competitive_landscape:'Testing multiple providers', compliance_context:'GDPR, EU AI Act (high risk?)', technical_environment:'GCP, Kotlin/Scala, Snowflake', discovery_notes:'CPO reached via LinkedIn. Low engagement so far. Need use case ROI case.', next_steps:'Send ROI calculator + fashion AI case study', date_added:now, updated_at:now },
  { id:'lead_010', company:'Wise', country:'UK', industry:'Fintech', employees:5000, source:'inbound_web', status:'qualifying', contact_name:'Kristo Käärmann', contact_title:'CTO', score_fit:4,score_intent:4,score_budget:3,score_decision_access:4,score_timeline:3,score_pain:4,score_compelling_event:4,score_champion:4,score_technical_fit:4,score_strategic_value:4, use_case_description:'Multi-lingual customer support automation across 70 currencies / 170+ countries.', competitive_landscape:'Evaluating AWS Bedrock vs direct API', compliance_context:'FCA, GDPR, multiple FinCEN requirements', technical_environment:'GCP, microservices, React', discovery_notes:'CTO is the champion. Budget flexible. Multi-lingual a key differentiator for Claude.', next_steps:'Multi-lingual capability demo booked', date_added:now, updated_at:now },
];

export const SEED_LEADS = RAW_LEADS.map(l => ({ ...l, ...computeLeadScore(l) }));

export const SEED_OUTBOUND = [
  { id:'ob_001', company:'Allianz', country:'Germany', vertical:'Insurance', employees:150000, outbound_tier:'tier_a', status:'sequence_active', trigger_signal:'EU AI Act compliance deadline driving AI governance project', entry_point_name:'Oliver Bäte', entry_point_title:'CDO', messaging_angle:'Constitutional AI + audit trails for DORA compliance', touchpoint_count:3, next_step:'Follow up on pilot proposal', next_step_date: now, touchpoints:[
    { id:'tp_001', date:now, channel:'linkedin', content_summary:'Sent InMail about EU AI Act compliance webinar', response:'no_response' },
    { id:'tp_002', date:now, channel:'email', content_summary:'Follow-up with EU AI Act one-pager + Claude safety overview', response:'positive' },
    { id:'tp_003', date:now, channel:'call', content_summary:'15-min intro call. CDO very interested in audit trail features.', response:'positive' },
  ]},
  { id:'ob_002', company:'Adyen', country:'Netherlands', vertical:'Fintech', employees:4000, outbound_tier:'tier_a', status:'meeting_booked', trigger_signal:'Series of engineering blog posts on ML infra — AI readiness signal', entry_point_name:'Ingo Uytdehaage', entry_point_title:'CTO', messaging_angle:'API reliability + SOC2 Type II for PCI-DSS environments', touchpoint_count:4, next_step:'Discovery call prep', next_step_date: now, touchpoints:[
    { id:'tp_004', date:now, channel:'email', content_summary:'Cold email referencing their ML blog post on inference costs', response:'positive' },
    { id:'tp_005', date:now, channel:'linkedin', content_summary:'Connected + shared Claude API latency benchmarks', response:'positive' },
    { id:'tp_006', date:now, channel:'call', content_summary:'Qualified: €300K budget, evaluating Q2, CTO is champion', response:'meeting_booked' },
    { id:'tp_007', date:now, channel:'email', content_summary:'Sent discovery agenda + Stripe case study', response:'positive' },
  ]},
  { id:'ob_003', company:'UBS', country:'Switzerland', vertical:'Finance', employees:72000, outbound_tier:'tier_a', status:'researched', trigger_signal:'FINMA AI regulation published — banks required to document AI systems by Jan 2025', entry_point_name:'Sergio Ermotti', entry_point_title:'Group CIO', messaging_angle:'Regulatory compliance AI + human oversight features', touchpoint_count:0, next_step:'Draft initial outreach email', next_step_date: now, touchpoints:[] },
  { id:'ob_004', company:'Doctolib', country:'France', vertical:'HealthTech', employees:3000, outbound_tier:'tier_b', status:'first_touch', trigger_signal:'Raised €150M Series E — scaling AI features across EU healthcare', entry_point_name:'Stanislas Niox-Chateau', entry_point_title:'VP Product', messaging_angle:'HIPAA-compliant AI + French language excellence', touchpoint_count:1, next_step:'Follow up with healthcare case studies', next_step_date: now, touchpoints:[
    { id:'tp_008', date:now, channel:'email', content_summary:'Intro email referencing their Series E and AI roadmap press release', response:'no_response' },
  ]},
  { id:'ob_005', company:'Spotify', country:'Sweden', vertical:'Media/Tech', employees:9700, outbound_tier:'tier_b', status:'sequence_active', trigger_signal:'Engineering team hiring 40+ ML roles — infra expansion signal', entry_point_name:'Gustav Söderström', entry_point_title:'Chief R&D Officer', messaging_angle:'High-throughput content moderation + podcast summarisation at scale', touchpoint_count:2, next_step:'Send podcast AI capability brief', next_step_date: now, touchpoints:[
    { id:'tp_009', date:now, channel:'linkedin', content_summary:'Connected via mutual contact (ex-Spotify eng now at Anthropic)', response:'positive' },
    { id:'tp_010', date:now, channel:'email', content_summary:'Sent content moderation API capabilities overview', response:'no_response' },
  ]},
];

const DEFAULT_CONFIG = {
  weight_fit:3, weight_intent:2, weight_capacity:2, weight_access:2, weight_timing:1,
  tier1_threshold:70, tier2_threshold:40, tier3_threshold:20,
  acv_enterprise:120000, acv_startup:25000,
  weekly_touch_target:50, weekly_meeting_target:5,
};

export { DEFAULT_CONFIG };
