// Pre-built lead data matching the new AI research schema — same companies as the
// live server seed so the portfolio demo looks identical to the real app.

const now = new Date().toISOString().split('T')[0];

export const SEED_LEADS = [
  {
    id: 'lead_001', company: 'Revolut', country: 'UK', industry: 'Fintech',
    employee_count_estimate: 8000,
    company_overview: 'UK-based neobank with 35M+ users. Operates across 35+ countries. Moving fast into B2B and embedded finance.',
    ai_readiness_score: 5, ai_readiness_reasoning: 'In-house AI team, existing API integrations, CTO publicly committed to AI-first product strategy.',
    use_case_fit_score: 5, use_case_fit_top_cases: ['Fraud narrative generation', 'Customer support deflection', 'Regulatory reporting'], use_case_fit_reasoning: 'Fraud detection and multilingual support at massive scale — both are exact Claude strengths.',
    compliance_sensitivity_score: 4, compliance_sensitivity_reasoning: 'FCA regulated. Needs audit logs for all AI outputs. EU AI Act applies to fraud scoring.',
    current_ai_tools: ['GPT-4o (evaluating)'], likely_pain_points: ['Hallucination rate in financial narratives', 'Audit trail gaps for FCA'], compelling_events: ['FCA AI guidance published Q1', 'Head of AI hired 6 weeks ago'],
    entry_point_title: 'Head of AI', entry_point_reasoning: 'Recently hired, owns the budget, evaluating providers now.',
    messaging_angle: 'Constitutional AI = compliance by design. 3× fewer hallucinations on financial narrative tasks vs GPT-4o.',
    overall_score: 97, tier: 'Tier 1',
    battlecard_openai: 'OpenAI cannot provide FCA-compliant audit logs. Constitutional AI blocks harmful outputs by design — not by post-processing.',
    battlecard_google: 'Gemini lacks the 200K context window needed to process full transaction histories in a single call.',
    battlecard_greenfield: 'In-house LLM build at Revolut scale = 18+ month timeline, £5M+ engineering cost, no compliance guarantees.',
    recommended_products: ['Claude API', 'Claude for Enterprise', 'Batch Processing'],
    contact_name: 'Irina Kovacs', contact_title: 'Head of AI',
    status: 'qualifying', expected_acv: 480000, conversion_probability: 0.45,
    route_to: 'enterprise_ae', date_added: now, last_touch: now,
  },
  {
    id: 'lead_002', company: 'Klarna', country: 'Sweden', industry: 'Fintech',
    employee_count_estimate: 3800,
    company_overview: 'BNPL and payments leader, 85M users, 500K merchants. Pre-IPO. Aggressively replacing headcount with AI.',
    ai_readiness_score: 5, ai_readiness_reasoning: 'Already replaced 700 support agents with AI. Sebastian publicly stated 90% of Klarna will use AI tools daily.',
    use_case_fit_score: 5, use_case_fit_top_cases: ['Customer service automation', 'Dispute resolution', 'Merchant onboarding docs'], use_case_fit_reasoning: "Klarna's entire CS strategy is AI-first. Claude's multilingual quality is critical for 35-country coverage.",
    compliance_sensitivity_score: 5, compliance_sensitivity_reasoning: 'PCI-DSS, GDPR, FCA, multiple national regulators. Needs air-tight data processing agreements.',
    current_ai_tools: ['OpenAI GPT-4 (incumbent)', 'Internal fine-tuned models'], likely_pain_points: ['GPT reliability during peak traffic', 'Multilingual quality in smaller EU languages'], compelling_events: ['IPO preparation driving revenue efficiency focus', 'Recent OpenAI outage caused 4h degradation'],
    entry_point_title: 'VP Engineering', entry_point_reasoning: 'Owns the AI infrastructure budget post the CS transformation project.',
    messaging_angle: "Klarna bet the company on AI CS — Claude's 99.9% uptime SLA and multilingual superiority protect that bet.",
    overall_score: 99, tier: 'Tier 1',
    battlecard_openai: "OpenAI outage in March caused €200K estimated CS degradation. Claude offers dedicated capacity + SLA.",
    battlecard_google: "Gemini Pro's multilingual coverage weak in Nordic languages — critical gap for Klarna's Sweden/Norway/Finland market.",
    battlecard_greenfield: 'Klarna already tried in-house. The transition to Claude from GPT is a swap, not a build — 2-week migration path.',
    recommended_products: ['Claude API', 'Batch Processing', 'Claude for Enterprise'],
    contact_name: 'David Sandström', contact_title: 'VP Engineering',
    status: 'qualifying', expected_acv: 720000, conversion_probability: 0.55,
    route_to: 'enterprise_ae', date_added: now, last_touch: now,
  },
  {
    id: 'lead_003', company: 'BNP Paribas', country: 'France', industry: 'Banking',
    employee_count_estimate: 193000,
    company_overview: 'Largest bank in the Eurozone. 190K employees, operates in 65 countries. Heavy regulatory burden, slow procurement.',
    ai_readiness_score: 3, ai_readiness_reasoning: 'Has an AI CoE but heavily restricted by DORA, MiFID II, and ACPR guidance. Cloud approvals take 6+ months.',
    use_case_fit_score: 4, use_case_fit_top_cases: ['Regulatory document processing', 'Internal knowledge search', 'Compliance summarisation'], use_case_fit_reasoning: 'Processes 10M+ regulatory documents per year. Manual review is the bottleneck — Claude Batch is an exact fit.',
    compliance_sensitivity_score: 5, compliance_sensitivity_reasoning: 'DORA compliance required by Jan 2025. ACPR requires full data residency in France. MiFID II explainability requirements.',
    current_ai_tools: ['Azure OpenAI (sandboxed)', 'Internal rule-based NLP'], likely_pain_points: ['Procurement bottleneck for new AI vendors', 'Data residency requirements block most APIs'], compelling_events: ['DORA compliance deadline Jan 2025', 'New CDO hired with AI mandate'],
    entry_point_title: 'Group CDO', entry_point_reasoning: 'New hire with explicit mandate to accelerate AI adoption within regulatory constraints.',
    messaging_angle: 'DORA compliance + EU data residency + constitutional AI = the only enterprise LLM BNP can actually deploy.',
    overall_score: 72, tier: 'Tier 2',
    battlecard_openai: "Azure OpenAI failed BNP's data residency audit. Anthropic offers EU data processing addendum with French residency option.",
    battlecard_google: 'GCP not approved by ACPR for financial data processing in France.',
    battlecard_greenfield: "BNP's internal NLP team cannot handle unstructured document volumes at Claude Batch scale.",
    recommended_products: ['Claude for Enterprise', 'Batch Processing', 'Claude API'],
    contact_name: 'Marie Dupont', contact_title: 'Group CDO',
    status: 'qualifying', expected_acv: 360000, conversion_probability: 0.18,
    route_to: 'enterprise_ae', date_added: now, last_touch: now,
  },
  {
    id: 'lead_004', company: 'Wise', country: 'UK', industry: 'Fintech',
    employee_count_estimate: 5000,
    company_overview: 'International money transfer platform. 16M customers, 170+ countries. Engineering-first culture, API-native.',
    ai_readiness_score: 4, ai_readiness_reasoning: 'Strong engineering culture. Already using ML for FX rate prediction and fraud. CTO is the champion.',
    use_case_fit_score: 4, use_case_fit_top_cases: ['Multilingual customer support (70+ currencies)', 'KYC document processing', 'Compliance narrative generation'], use_case_fit_reasoning: 'Multilingual support across 170 countries is a Claude differentiator — other models struggle with smaller language coverage.',
    compliance_sensitivity_score: 4, compliance_sensitivity_reasoning: 'FCA, GDPR, FinCEN, and local equivalents in 50+ countries. Data processing by jurisdiction is complex.',
    current_ai_tools: ['AWS Bedrock (evaluating)'], likely_pain_points: ['Inconsistent language quality across 70+ languages', 'KYC fraud documentation too manual'], compelling_events: ['Q2 product roadmap includes AI support expansion', 'AWS Bedrock pilot produced poor multilingual results'],
    entry_point_title: 'CTO', entry_point_reasoning: 'CTO owns the AI vendor decision. AWS Bedrock pilot underperformed — actively looking for alternatives.',
    messaging_angle: "Claude outperforms every model on non-English European and Asian languages — Wise's core competitive surface.",
    overall_score: 81, tier: 'Tier 1',
    battlecard_openai: 'OpenAI GPT-4o multilingual quality degrades significantly outside top-5 languages. Wise operates in 70+.',
    battlecard_google: "AWS Bedrock already trialled and failed on multilingual quality. Wise won't run a second Bedrock evaluation.",
    battlecard_greenfield: 'Building multilingual support models in-house requires training data in 70+ languages — not feasible.',
    recommended_products: ['Claude API', 'Claude for Enterprise'],
    contact_name: 'Kristo Käärmann', contact_title: 'CTO',
    status: 'new', expected_acv: 240000, conversion_probability: 0.28,
    route_to: 'enterprise_ae', date_added: now, last_touch: now,
  },
  {
    id: 'lead_005', company: 'Doctolib', country: 'France', industry: 'HealthTech',
    employee_count_estimate: 3000,
    company_overview: 'Largest digital health platform in Europe. 70M patients, 300K healthcare professionals. France, Germany, Italy.',
    ai_readiness_score: 3, ai_readiness_reasoning: 'Engineering team expanding. Healthcare AI use cases are clear but regulatory hurdles slow everything down.',
    use_case_fit_score: 4, use_case_fit_top_cases: ['Medical consultation summaries', 'Patient pre-screening', 'Appointment triage'], use_case_fit_reasoning: 'Clinical documentation automation is the single highest-ROI AI use case in European healthcare.',
    compliance_sensitivity_score: 5, compliance_sensitivity_reasoning: 'EU MDR, GDPR health data (Article 9), HDS (French health data host certification) required.',
    current_ai_tools: ['None (evaluating first vendor)'], likely_pain_points: ['Doctors spend 40% of time on documentation', 'No compliant AI vendor has passed HDS audit'], compelling_events: ['French HDS certification pathway opened Jan 2025', 'Series F announcement signalled AI expansion'],
    entry_point_title: 'VP Product', entry_point_reasoning: 'Owns the AI product roadmap. Actively evaluating vendors since Series F close.',
    messaging_angle: 'Only enterprise AI vendor pursuing HDS certification — required for Doctolib to deploy in French healthcare.',
    overall_score: 78, tier: 'Tier 2',
    battlecard_openai: 'OpenAI has no HDS certification pathway. OpenAI data processing cannot be hosted in France for health data.',
    battlecard_google: 'Google Health AI is US-only currently. No EU regulatory pathway published.',
    battlecard_greenfield: 'Building an HDS-compliant AI stack in-house would require 2+ years and €3M+ in compliance infrastructure.',
    recommended_products: ['Claude for Enterprise', 'Claude API'],
    contact_name: 'Céline Martin', contact_title: 'VP Product',
    status: 'new', expected_acv: 180000, conversion_probability: 0.22,
    route_to: 'enterprise_ae', date_added: now, last_touch: now,
  },
];

export const SEED_OUTBOUND = [
  {
    id: 'ob_001', company: 'Allianz', country: 'Germany', vertical: 'Insurance',
    outbound_tier: 'tier_a', status: 'sequence_active',
    trigger_signal: 'CDO hired 3 months ago; 12 AI/ML job postings in last 60 days.',
    entry_point_name: 'Michael Hoffmann', entry_point_title: 'Chief Digital Officer',
    messaging_angle: "EU AI Act compliance timeline pressure — Allianz needs auditable, explainable AI before the Dec deadline. Claude's constitutional AI approach maps directly.",
    next_step: 'Follow up on LinkedIn message sent Monday',
    next_step_date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    last_touch: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
    touchpoint_count: 3,
    touchpoints: [
      { id: 'tp_001', date: new Date(Date.now() - 12 * 86400000).toISOString().split('T')[0], channel: 'linkedin', content_summary: 'Sent InMail about EU AI Act compliance webinar', response: 'no_response' },
      { id: 'tp_002', date: new Date(Date.now() - 8 * 86400000).toISOString().split('T')[0], channel: 'email', content_summary: 'Follow-up with EU AI Act one-pager + Claude safety overview', response: 'positive' },
      { id: 'tp_003', date: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0], channel: 'call', content_summary: '15-min intro call. CDO very interested in audit trail features.', response: 'positive' },
    ],
  },
  {
    id: 'ob_002', company: 'Adyen', country: 'Netherlands', vertical: 'Fintech',
    outbound_tier: 'tier_a', status: 'meeting_booked',
    trigger_signal: 'Series of engineering blog posts on ML infra — strong AI readiness signal.',
    entry_point_name: 'Ingo Uytdehaage', entry_point_title: 'CTO',
    messaging_angle: "API reliability + SOC2 Type II for PCI-DSS payment environments — Adyen can't afford downtime.",
    next_step: 'Discovery call prep',
    next_step_date: new Date(Date.now() + 1 * 86400000).toISOString().split('T')[0],
    last_touch: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    touchpoint_count: 4,
    touchpoints: [
      { id: 'tp_004', date: new Date(Date.now() - 14 * 86400000).toISOString().split('T')[0], channel: 'email', content_summary: 'Cold email referencing their ML blog post on inference costs', response: 'positive' },
      { id: 'tp_005', date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0], channel: 'linkedin', content_summary: 'Shared Claude API latency benchmarks', response: 'positive' },
      { id: 'tp_006', date: new Date(Date.now() - 6 * 86400000).toISOString().split('T')[0], channel: 'call', content_summary: 'Qualified: €300K budget, CTO is champion', response: 'meeting_booked' },
      { id: 'tp_007', date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0], channel: 'email', content_summary: 'Sent discovery agenda + Stripe case study', response: 'positive' },
    ],
  },
  {
    id: 'ob_003', company: 'UBS', country: 'Switzerland', vertical: 'Finance',
    outbound_tier: 'tier_a', status: 'researched',
    trigger_signal: 'FINMA AI regulation published — banks must document AI systems by Jan 2025.',
    entry_point_name: 'Sergio Ermotti', entry_point_title: 'Group CIO',
    messaging_angle: 'Regulatory compliance AI + full human oversight features — maps directly to FINMA requirements.',
    next_step: 'Draft initial cold outreach email',
    next_step_date: now,
    last_touch: null,
    touchpoint_count: 0,
    touchpoints: [],
  },
  {
    id: 'ob_004', company: 'Spotify', country: 'Sweden', vertical: 'Media/Tech',
    outbound_tier: 'tier_b', status: 'sequence_active',
    trigger_signal: 'Engineering team hiring 40+ ML roles — major AI infra expansion signal.',
    entry_point_name: 'Gustav Söderström', entry_point_title: 'Chief R&D Officer',
    messaging_angle: 'High-throughput content moderation + podcast summarisation at scale — 600M tracks/episodes.',
    next_step: 'Send podcast AI capability brief',
    next_step_date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    last_touch: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    touchpoint_count: 2,
    touchpoints: [
      { id: 'tp_008', date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0], channel: 'linkedin', content_summary: 'Connected via mutual contact', response: 'positive' },
      { id: 'tp_009', date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0], channel: 'email', content_summary: 'Sent content moderation API overview', response: 'no_response' },
    ],
  },
  {
    id: 'ob_005', company: 'Zalando', country: 'Germany', vertical: 'E-commerce',
    outbound_tier: 'tier_b', status: 'first_touch',
    trigger_signal: 'Launched AI styling assistant — publicly announced expansion of AI features.',
    entry_point_name: 'Robert Gentz', entry_point_title: 'Chief Product Officer',
    messaging_angle: 'Fashion product description generation + styling recommendations — 50M SKUs, 35 markets.',
    next_step: 'Send ROI calculator + fashion AI case study',
    next_step_date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
    last_touch: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
    touchpoint_count: 1,
    touchpoints: [
      { id: 'tp_010', date: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0], channel: 'email', content_summary: 'Intro email referencing their AI styling launch', response: 'no_response' },
    ],
  },
];
